# Generated by Django 5.0.1 on 2024-01-16 14:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Title of the event",
                        max_length=70,
                        verbose_name="Title of the event",
                    ),
                ),
                (
                    "day",
                    models.DateField(
                        help_text="Day of the event", verbose_name="Day of the event"
                    ),
                ),
                (
                    "start_time",
                    models.TimeField(
                        help_text="Starting time", verbose_name="Starting time"
                    ),
                ),
                (
                    "end_time",
                    models.TimeField(help_text="Final time", verbose_name="Final time"),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Textual Notes",
                        null=True,
                        verbose_name="Textual Notes",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        choices=[("science", "Science"), ("technology", "Technology")],
                        max_length=100,
                    ),
                ),
            ],
            options={
                "verbose_name": "Scheduling",
                "verbose_name_plural": "Scheduling",
            },
        ),
    ]
