# Generated by Django 5.0.1 on 2024-01-17 12:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="end_day",
            field=models.DateField(
                blank=True,
                help_text="End day of the event",
                null=True,
                verbose_name="End day of the event",
            ),
        ),
    ]
